package webui

import (
	"strings"
	"testing"
)

// Icon partials are generated by `pnpm icons` from lucide-static. They must be
// parsed (so call sites resolve), render an inline <svg>, default to size-4, be
// decorative (aria-hidden) and color via currentColor, and accept a class arg.
func TestIcon_RendersInlineSVG(t *testing.T) {
	// A representative icon used by the templates.
	out := exec(t, "icon-git-branch", nil)
	for _, want := range []string{"<svg", "aria-hidden=\"true\"", `stroke="currentColor"`, "</svg>"} {
		if !strings.Contains(out, want) {
			t.Errorf("icon missing %q: %s", want, out)
		}
	}
	if strings.Contains(out, `width="24"`) || strings.Contains(out, `height="24"`) {
		t.Errorf("icon should drop fixed width/height so Tailwind size-* controls it: %s", out)
	}
	// nil data (called as {{template "icon-x"}}) falls back to the default size.
	if !strings.Contains(out, `class="size-4"`) {
		t.Errorf("icon default size should be size-4: %s", out)
	}
	// A class arg overrides the default.
	if out := exec(t, "icon-git-branch", "size-3 text-muted-foreground"); !strings.Contains(out, `class="size-3 text-muted-foreground"`) {
		t.Errorf("icon should use the passed class: %s", out)
	}
}

// The icons the screens reference must all be defined (guards against a template
// referencing an icon that wasn't generated).
func TestIcons_UsedByTemplatesAreDefined(t *testing.T) {
	for _, name := range []string{
		"icon-arrow-left", "icon-inbox", "icon-circle-alert", "icon-git-branch",
		"icon-triangle-alert", "icon-terminal", "icon-external-link",
	} {
		if templates.Lookup(name) == nil {
			t.Errorf("icon partial %q not defined (run `pnpm icons`)", name)
		}
	}
}
