// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"database/sql"
)

type ChainAttempt struct {
	SessionID   string
	Instance    string
	ChainID     string
	Fingerprint string
}

type Event struct {
	ID           string
	SessionID    string
	Sequence     int64
	Time         string
	Type         string
	Source       string
	Direction    string
	Summary      string
	Body         string
	MetadataJson string
}

type EventCursor struct {
	SessionID    string
	Kind         string
	NextSequence int64
}

type NodeExecution struct {
	ID                      string
	SessionID               string
	NodeID                  string
	Sequence                int64
	TaskID                  sql.NullString
	Name                    sql.NullString
	Scope                   string
	Status                  string
	Resource                sql.NullString
	InputsJson              sql.NullString
	OutputsJson             sql.NullString
	StateJson               sql.NullString
	ResourceObservationJson sql.NullString
	ResourceObservedAt      sql.NullString
	DoneWhenJson            sql.NullString
	ExtraDoneWhenJson       sql.NullString
	Error                   sql.NullString
	SetupAt                 sql.NullString
	FailedAt                sql.NullString
	CleanedAt               sql.NullString
	FinalizedAt             sql.NullString
}

type NodeExecutionDependency struct {
	ExecutionID          string
	DependsOnExecutionID string
}

type NodeExecutionLayer struct {
	ExecutionID          string
	Position             int64
	EffectID             string
	Status               string
	InputsJson           sql.NullString
	LocalsJson           sql.NullString
	OutputsJson          sql.NullString
	EnvJson              sql.NullString
	HeartbeatTicks       sql.NullInt64
	HeartbeatEscalations sql.NullInt64
	SetupAt              sql.NullString
	FailedAt             sql.NullString
	CleanedAt            sql.NullString
	Error                sql.NullString
}

type NodeInstance struct {
	SessionID string
	NodeID    string
}

type Population struct {
	Workflow string
	Name     string
}

type PopulationMember struct {
	Workflow                 string
	Name                     string
	ResourceID               string
	SessionName              sql.NullString
	Generation               int64
	AcceptedAt               sql.NullString
	LastAppearance           sql.NullString
	LastInbound              sql.NullString
	Tombstoned               bool
	PendingUp                bool
	ConsecutiveAdmitFailures int64
	LastAdmitReason          sql.NullString
	LastAdmitError           sql.NullString
	AdmitRetryAt             sql.NullString
	AdmitSuspended           bool
	DecisionKind             sql.NullString
	DecisionReason           sql.NullString
	ItemJson                 string
}

type PopulationMemberBlocker struct {
	Workflow   string
	Name       string
	ResourceID string
	Position   int64
	Reason     string
}

type Session struct {
	ID                       string
	Name                     string
	Status                   string
	DestroyedAt              sql.NullString
	ParentSessionID          sql.NullString
	RootSessionID            sql.NullString
	ResourceID               sql.NullString
	Alias                    sql.NullString
	Workflow                 string
	WorkspaceDir             sql.NullString
	PopulationWorkflow       sql.NullString
	PopulationName           sql.NullString
	InputsJson               sql.NullString
	HealthLastCheckedAt      sql.NullString
	HealthLastActivityAt     sql.NullString
	HealthLastFingerprint    sql.NullString
	HealthLastState          sql.NullString
	HealthLastReason         sql.NullString
	HealthLastNotifiedAt     sql.NullString
	HealthNotifyCount        sql.NullInt64
	TickConsecutiveUnchanged sql.NullInt64
	TickLastFingerprint      sql.NullString
	LastTickAt               sql.NullString
	CreatedAt                string
	UpdatedAt                string
}

type SessionChannelHealth struct {
	SessionID           string
	Kind                string
	ConsecutiveFailures int64
	FirstFailureAt      string
	LastFailureAt       string
	LastChannel         sql.NullString
	LastError           sql.NullString
	EscalatedAt         sql.NullString
}

type SubscriptionRetry struct {
	SessionID  string
	Action     string
	ResourceID string
}

type TaskDoneWhenJudge struct {
	TaskInstanceID string
	LeafID         string
	Action         string
	Reason         string
	Revision       string
	JudgeSession   string
	JudgeWorkflow  sql.NullString
	Relation       string
	CreatedAt      string
}

type TaskDoneWhenState struct {
	TaskInstanceID       string
	HeartbeatTicks       int64
	HeartbeatEscalations int64
	LastAction           sql.NullString
	LastFingerprint      sql.NullString
	LastReason           sql.NullString
	LastBody             sql.NullString
	EscalatedAt          sql.NullString
	EscalateReason       sql.NullString
}

type TaskDoneWhenUnsatisfiedItem struct {
	TaskInstanceID string
	Position       int64
	Item           string
}

type TaskInstance struct {
	ID                      string
	SessionID               string
	InstanceName            string
	TaskID                  string
	Scope                   string
	Status                  string
	Sequence                int64
	Resource                sql.NullString
	Named                   bool
	InputsJson              sql.NullString
	OutputsJson             sql.NullString
	StateJson               sql.NullString
	ResourceObservationJson sql.NullString
	ResourceObservedAt      sql.NullString
	ExtraDoneWhenJson       sql.NullString
	Error                   sql.NullString
	SetupAt                 sql.NullString
	FailedAt                sql.NullString
	CleanedAt               sql.NullString
	FinalizedAt             sql.NullString
}

type TaskInstanceLayer struct {
	TaskInstanceID       string
	Position             int64
	EffectID             string
	Status               string
	InputsJson           sql.NullString
	LocalsJson           sql.NullString
	OutputsJson          sql.NullString
	EnvJson              sql.NullString
	HeartbeatTicks       sql.NullInt64
	HeartbeatEscalations sql.NullInt64
	SetupAt              sql.NullString
	FailedAt             sql.NullString
	CleanedAt            sql.NullString
	Error                sql.NullString
}

type UpReservation struct {
	ChildSessionName  string
	ParentSessionName sql.NullString
	VirtualRoot       bool
	Pid               int64
	ReservedAt        string
}
