// gen-icons.mjs — dev-only. Generates html/template partials for the icons we
// actually use, from the pinned lucide-static package. Keeps provenance fixed
// (no hand-copied SVG) while shipping zero runtime JS: the SVG is server-rendered
// and survives htmx swaps. Run via `pnpm icons` (also part of `pnpm build`).
//
// To add an icon: add its lucide name below and run `pnpm icons`.
import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

// lucide icon names → html/template partial "icon-<name>". Keep this to icons
// the templates actually use; add a name and re-run when a new screen needs one.
const ICONS = [
  "arrow-left", // back to list (detail header)
  "inbox", // empty state (no sessions)
  "circle-alert", // error banner
  "git-branch", // branch metadata
  "triangle-alert", // warnings (diagnostics, not-found)
  "terminal", // attach section
  "external-link", // off-site links (linked PR)
];

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, ".."); // webui dir
const srcDir = join(root, "node_modules/lucide-static/icons");
const outDir = join(root, "assets/templates/components/icons");
const version = JSON.parse(
  readFileSync(join(root, "node_modules/lucide-static/package.json"), "utf8"),
).version;

// Regenerate from scratch so a removed name doesn't leave a stale partial behind.
rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

for (const name of ICONS) {
  const raw = readFileSync(join(srcDir, `${name}.svg`), "utf8");
  const svg = raw
    .replace(/<!--[\s\S]*?-->/g, "") // drop the license comment
    .replace(/\s+width="24"/, "") // let Tailwind size-* drive dimensions
    .replace(/\s+height="24"/, "")
    // class is caller-supplied (size + color via tokens); decorative by default.
    .replace(/class="[^"]*"/, 'class="{{or . "size-4"}}" aria-hidden="true"')
    .replace(/\s*\n\s*/g, " ") // collapse the pretty-printed multiline to one line
    .replace(/>\s+</g, "><")
    .replace(/\s+>/g, ">")
    .replace(/ {2,}/g, " ")
    .trim();

  const partial =
    `{{- /* Generated by 'pnpm icons' from lucide-static v${version}. Do not edit;` +
    ` add names to scripts/gen-icons.mjs and re-run. */ -}}\n` +
    `{{define "icon-${name}"}}${svg}{{end}}\n`;
  writeFileSync(join(outDir, `${name}.html`), partial);
}

console.log(`generated ${ICONS.length} icon partials from lucide-static v${version}`);
